name: flutter_about_me

packages:
  - packages/**

dependency_overrides:
  melos: ^7.1.0

  flutter_lints: ^6.0.0

  material_symbols_icons: ^4.2867.0

  dio: ^5.9.0
  json_annotation: ^4.9.0
  connectivity_plus: ^6.1.5

  get_it: ^8.2.0
  injectable: ^2.5.1

  build_runner: ^2.7.0
  json_serializable: ^6.10.0
  injectable_generator: ^2.8.1

  drift: ^2.28.1
  sqlite3_flutter_libs: ^0.5.39
  path_provider: ^2.1.5
  path: ^1.9.1
  drift_dev: ^2.28.1

scripts:
  build_runner:
    run: |
      melos exec --depends-on="build_runner" -- flutter pub run build_runner build --delete-conflicting-outputs
