name: domain_di
description: "A new Flutter package project."
version: 0.0.1

publish_to: 'none'

environment:
  sdk: ^3.8.1
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  main_domain:
    path: ../../domain/main_domain
  articles_domain:
    path: ../../domain/articles_domain
  article_domain:
    path: ../../domain/article_domain
  profile_domain:
    path: ../../domain/profile_domain

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: any
