name: core_di
description: "A new Flutter package project."
version: 0.0.1

publish_to: 'none'

environment:
  sdk: ^3.8.1
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  network:
    path: ../../core/network
  database:
    path: ../../core/database
  preferences:
    path: ../../core/preferences

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: any
