name: bottom_navigation_screen
description: "A new Flutter package project."
version: 0.0.1

publish_to: 'none'

environment:
  sdk: ^3.8.0
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  design_system:
    path: ../../core/design_system
  articles_screen:
    path: ../../screens/articles_screen
  profile_screen:
    path: ../../screens/profile_screen
  material_symbols_icons: any
  flutter_bloc: any
  freezed_annotation: any

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: any
  build_runner: any
  freezed: any

flutter:
  uses-material-design: true
