name: design_system
description: "A new Flutter package project."
version: 0.0.1

publish_to: 'none'

environment:
  sdk: ^3.8.0
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  material_symbols_icons: any

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: any

flutter:
  uses-material-design: true
  fonts:
    - family: IRANYekanX
      fonts:
        - asset: assets/fonts/IRANYekanX-Regular.ttf
          weight: 400
        - asset: assets/fonts/IRANYekanX-Medium.ttf
          weight: 500
        - asset: assets/fonts/IRANYekanX-Bold.ttf
          weight: 700
